import Header from "./components/Header";
import Footer from "./components/Footer";
import Contact from "./components/Contact";

const resumeUrl = "https://drive.google.com/file/d/1wX_rkgIs0W4AezahD9oTX5JIfNtb3AYi/view?usp=sharing";
const githubUrl = "https://github.com/sahilshaikhh202";
const linkedinUrl = "https://www.linkedin.com/in/mohd-sahil-shaikh-3664aa307";

const skills = [["Languages", "TypeScript · JavaScript · Python · Java · SQL"], ["Backend", "NestJS · Node.js · PostgreSQL · TypeORM · Redis · Bull"], ["Frontend", "React · Next.js · Redux Toolkit"], ["Systems", "REST APIs · Async Jobs · Queues · Authentication · RBAC"], ["Infrastructure", "AWS S3 · Docker · CI/CD · Sentry · OpenTelemetry"], ["Integrations", "Razorpay · Meta CAPI · WebEngage · OpenAI · SendGrid · Gupshup · MSG91"]];

function SectionHeading({ index, children, intro }) { return <div className="section-heading"><span>{index}</span><div><h2>{children}</h2>{intro && <p>{intro}</p>}</div></div>; }
function App() {
  return <div className="site-shell"><Header resumeUrl={resumeUrl} /><main>
    <section className="hero" id="top"><div className="hero-grid"><div className="hero-main"><p className="eyebrow">Software engineer / University of Edinburgh</p><h1>Mohd Sahil Azad<br /><em>Shaikh</em></h1><p className="hero-role">Software Engineer <i>·</i> MSc Computer Science @ The University of Edinburgh</p><p className="hero-copy">I build production software across backend systems, product interfaces and AI-powered applications.</p><div className="hero-actions"><a className="button button-dark" href="#experience">View work <span>↓</span></a><a className="button button-line" href={resumeUrl} target="_blank" rel="noreferrer">Resume ↗</a></div><div className="hero-socials"><a href={githubUrl} target="_blank" rel="noreferrer">GitHub ↗</a><a href={linkedinUrl} target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></div></section>
    <section className="currently section-wrap" id="edinburgh"><SectionHeading index="01" intro="A new academic chapter, grounded in production engineering.">Currently</SectionHeading><div className="currently-card"><span className="currently-kicker">The University of Edinburgh</span><div><h3>MSc Computer Science</h3><p>2026—2027 <i>·</i> Starting September 14, 2026</p></div><p className="currently-copy">Pursuing a one-year MSc while continuing to build software and explore systems, software engineering and AI.</p></div></section>
    <section className="experience section-wrap" id="experience"><SectionHeading index="02" intro="Full-stack feature ownership across a production running-event ecosystem.">Experience</SectionHeading><div className="experience-layout"><div className="company-lockup"><p className="eyebrow">Oct 2025 — Jun 2026 / Mumbai, India</p><h3>Software<br />Engineer</h3><p>Fitpage <i>/</i> IndiaRunning</p></div><div className="experience-content"><p className="experience-lead">Worked across a seven-repository production ecosystem spanning NestJS services, React and Next.js applications, shared data layers and integrations.</p><ul><li>Owned substantial features from API and data modelling through frontend workflows and production release.</li><li>Built across backend and frontend using TypeScript, NestJS, PostgreSQL/TypeORM, React, Next.js, Redis and Bull.</li><li>Shipped automated BIB allocation, server-side Meta conversion tracking, asynchronous notification infrastructure and AI-powered race tooling.</li><li>Integrated third-party services while keeping critical product flows resilient and asynchronous where appropriate.</li></ul><div className="metric-row"><div><strong>7</strong><span>repositories</span></div><div><strong>463</strong><span>commits</span></div><div><strong>15+</strong><span>substantial features</span></div></div></div></div></section>
    <section className="projects section-wrap" id="projects"><SectionHeading index="03" intro="Things I build because the problem keeps me interested.">Independent projects</SectionHeading><div className="penvault"><div className="penvault-content"><span className="eyebrow">Featured independent product</span><h3>PenVault</h3><p>A platform built around reading, writing, discovering and engaging with stories.</p><div className="tags"><span>Python</span><span>Flask</span><span>PostgreSQL</span><span>Supabase</span></div><a className="text-button" href="https://penvault.co" target="_blank" rel="noreferrer">Visit PenVault <span>↗</span></a></div><a className="project-image-link" href="https://penvault.co" target="_blank" rel="noreferrer"><img src="https://i.ibb.co/G40Sjpxn/image.png" alt="PenVault product interface" /></a></div><div className="project-list"><article><span>01</span><div><h3>MedNova</h3><p>A digital learning platform connecting doctors and students around lectures, notes and moderated content.</p></div><a href="https://med-nova-sable.vercel.app/" target="_blank" rel="noreferrer">View ↗</a></article><article><span>02</span><div><h3>Flicksify</h3><p>A personal media library for tracking movies, shows, anime, manga and novels.</p></div><a href="https://github.com/sahilshaikhh202/Flicksify" target="_blank" rel="noreferrer">GitHub ↗</a></article></div></section>
    <section className="skills-section section-wrap" id="skills"><SectionHeading index="04" intro="Technologies in service of dependable product systems—not a logo collection.">Engineering stack</SectionHeading><div className="skills-list">{skills.map(([label, value]) => <div key={label}><h3>{label}</h3><p>{value}</p></div>)}</div></section>
    <section className="education section-wrap" id="about"><SectionHeading index="05">Education & direction</SectionHeading><div className="education-layout"><div><span className="eyebrow">2026 — 2027</span><h3>University of Edinburgh</h3><p>MSc Computer Science</p></div><div className="timeline"><div><span>2023</span><p>Undergraduate foundation</p></div><div><span>2025</span><p>Software Engineer<br />Fitpage / IndiaRunning</p></div><div className="timeline-current"><span>2026</span><p>MSc Computer Science<br />University of Edinburgh</p></div><div><span>2027</span><p>Next chapter</p></div></div></div></section>
    <section className="about section-wrap"><SectionHeading index="06">How I build</SectionHeading><div className="about-layout"><h3>I like problems that<br /><em>cross layers.</em></h3><div><p>My best work tends to happen where database design, API contracts, frontend state, async processing and external services all need to fit together.</p><div className="layer-chain"><span>Database</span><b>→</b><span>API</span><b>→</b><span>Frontend</span><b>→</b><span>Async</span><b>→</b><span>External services</span></div><p className="about-secondary">I’m interested in building systems that sit between product and engineering—then using deeper computer science study to make those systems more thoughtful and robust.</p></div></div><div className="notes"><span className="eyebrow">Engineering notes</span><p>A home for considered writing about systems, software engineering and what I learn while building. Coming soon.</p></div></section>
    <Contact /></main><Footer githubUrl={githubUrl} linkedinUrl={linkedinUrl} /></div>;
}
export default App;
