import { useEffect, useState } from "react";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Contact from "./components/Contact";

const resumeUrl = "https://drive.google.com/file/d/1wX_rkgIs0W4AezahD9oTX5JIfNtb3AYi/view?usp=sharing";
const githubUrl = "https://github.com/sahilshaikhh202";
const linkedinUrl = "https://www.linkedin.com/in/mohd-sahil-shaikh-3664aa307";

const caseStudies = [
  { number: "01", title: "BIB Assignment V2", tags: ["Algorithms", "NestJS", "React", "PostgreSQL"], summary: "Automated BIB range allocation for race organisers, generating collision-free ranges across distance, category and company groups.", type: "bib", problem: "Race organisers needed a reliable way to configure participant BIB ranges across several overlapping groups without relying on manual spreadsheet work.", role: "Built the system end-to-end: range suggestion logic in NestJS and the organiser-facing React workflow for configuring, reviewing and auditing assignments.", approach: "The allocation flow resolves the relevant participant groups, checks existing ranges and searches for a non-overlapping candidate before presenting a reviewable result.", implementation: "TypeScript, NestJS, PostgreSQL/TypeORM, React and Redux Toolkit.", decisions: "Kept validation close to the allocation logic, made the preview workflow searchable, and preserved an audit trail around policy changes.", result: "Gave organisers a structured, safer workflow for configuring BIB allocations across complex event groups.", learning: "Small allocation rules become product-critical when they need to remain understandable, verifiable and safe to change." },
  { number: "02", title: "Meta Conversions API", tags: ["Payments", "Event Tracking", "Meta API", "Distributed Events"], summary: "Built server-side conversion tracking alongside the browser pixel, using transaction-level deduplication to prevent duplicate conversion events.", type: "capi", problem: "Browser-only conversion tracking can lose important signal, while sending the same event from browser and server risks reporting a conversion twice.", role: "Implemented the server-side payment-success event and coordinated the matching browser event contract.", approach: "A shared transaction-level event ID links the browser and server events. Meta can recognise the pair as a single conversion while the server enriches the event appropriately.", implementation: "NestJS, TypeScript, payment-success workflows and the Meta Conversions API.", decisions: "Used one event identifier across both sides, hashed supported user data before transmission, and kept the tracking work tied to the successful transaction flow.", result: "Established a more resilient conversion-tracking path without double-counting paired browser and server events.", learning: "Reliable tracking is a cross-system contract: the backend, frontend and external platform must agree on exactly what one event means." },
  { number: "03", title: "Notification Infrastructure", tags: ["Redis", "Bull", "Async Processing", "WebEngage"], summary: "Built asynchronous notification infrastructure connecting product workflows to user communication without blocking critical requests.", type: "notifications", problem: "Notifications belong to many product flows, but delivery failures or latency should never slow down payment, registration or other critical work.", role: "Built the notification module and queue processing, then connected product events to it using a fire-and-forget pattern.", approach: "Product workflows hand off notification work to a dedicated service. Bull workers process the jobs independently and send them through the relevant channels.", implementation: "NestJS, Redis, Bull, WebEngage, email, SMS and WhatsApp integrations.", decisions: "Separated notification delivery from the request lifecycle so a delivery issue does not become a primary-flow failure.", result: "Provided a reusable path for payment, registration, refund, invite and transfer communication workflows.", learning: "Asynchronous boundaries are as much about product reliability as they are about throughput." },
  { number: "04", title: "RunBuddy AI", tags: ["OpenAI", "NestJS", "AI", "Data Processing"], summary: "Built race-specific route analysis combining elevation, weather and pacing information into an AI-powered race companion.", type: "runbuddy", problem: "Race participants need advice that reflects the actual course and race conditions, rather than generic running guidance.", role: "Built the typed backend response that brings route segments, elevation and weather context together for the race companion.", approach: "The service analyses route segments and elevation, combines race-day context, then provides structured information for the OpenAI-powered experience.", implementation: "NestJS, TypeScript, data processing and OpenAI integration.", decisions: "Structured the response before it reaches the AI layer so the product can work with clear, race-specific context.", result: "Enabled a race companion experience grounded in route and event information for the featured event.", learning: "Useful AI product work starts with relevant, well-shaped data—not just a model call." }
];
const skills = [["Languages", "TypeScript · JavaScript · Python · Java · SQL"], ["Backend", "NestJS · Node.js · PostgreSQL · TypeORM · Redis · Bull"], ["Frontend", "React · Next.js · Redux Toolkit"], ["Systems", "REST APIs · Async Jobs · Queues · Authentication · RBAC"], ["Infrastructure", "AWS S3 · Docker · CI/CD · Sentry · OpenTelemetry"], ["Integrations", "Razorpay · Meta CAPI · WebEngage · OpenAI · SendGrid · Gupshup · MSG91"]];

function SectionHeading({ index, children, intro }) { return <div className="section-heading"><span>{index}</span><div><h2>{children}</h2>{intro && <p>{intro}</p>}</div></div>; }
function FlowDiagram({ type }) {
  const flows = { bib:["Participants", "Group by distance\ncategory · company", "Range search", "Collision-free\nBIB suggestion"], capi:["Browser event\ntransaction event ID", "Meta", "Backend event\nsame event ID", "One deduplicated\nconversion"], notifications:["Payment · Registration\nRefund · Invite · Transfer", "Notification\nservice", "Bull queue\n& workers", "WebEngage · Email\nSMS · WhatsApp"], runbuddy:["Route segments", "Elevation\nanalysis", "Weather & pacing\ncontext", "AI race\ncompanion"] };
  return <div className={`flow-diagram ${type}`}>{flows[type].map((label, index) => <div className="flow-item" key={label}><div className="flow-node">{label.split("\n").map(line => <span key={line}>{line}</span>)}</div>{index < 3 && <span className="flow-arrow">→</span>}</div>)}</div>;
}
function CaseStudy({ study, onOpen }) { return <article className="work-card"><div className="work-card-top"><span className="work-number">{study.number}</span><span className="work-action">Case study ↗</span></div><h3>{study.title}</h3><p>{study.summary}</p><div className="tags">{study.tags.map(tag => <span key={tag}>{tag}</span>)}</div><FlowDiagram type={study.type} /><button type="button" onClick={() => onOpen(study)} className="text-button">Explore the engineering story <span>↗</span></button></article>; }
function CaseStudyModal({ study, onClose }) {
  useEffect(() => { const close = event => event.key === "Escape" && onClose(); document.body.style.overflow = "hidden"; window.addEventListener("keydown", close); return () => { document.body.style.overflow = ""; window.removeEventListener("keydown", close); }; }, [onClose]);
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><article className="case-modal" role="dialog" aria-modal="true" aria-labelledby="case-title" onMouseDown={event => event.stopPropagation()}><button className="modal-close" type="button" onClick={onClose} aria-label="Close case study">×</button><span className="eyebrow">Selected work / {study.number}</span><h2 id="case-title">{study.title}</h2><p className="modal-summary">{study.summary}</p><FlowDiagram type={study.type} /><div className="case-grid"><section><h3>The problem</h3><p>{study.problem}</p></section><section><h3>My role</h3><p>{study.role}</p></section><section><h3>The approach</h3><p>{study.approach}</p></section><section><h3>Implementation</h3><p>{study.implementation}</p></section><section><h3>Key engineering decision</h3><p>{study.decisions}</p></section><section><h3>Result</h3><p>{study.result}</p></section></div><div className="case-learning"><span>What I learned</span><p>{study.learning}</p></div></article></div>;
}

function App() {
  const [activeStudy, setActiveStudy] = useState(null);
  return <div className="site-shell"><Header resumeUrl={resumeUrl} /><main>
    <section className="hero" id="top"><div className="hero-grid"><div className="hero-main"><p className="eyebrow">Software engineer / University of Edinburgh</p><h1>Mohd Sahil Azad<br /><em>Shaikh</em></h1><p className="hero-role">Software Engineer <i>·</i> MSc Computer Science @ The University of Edinburgh</p><p className="hero-copy">I build production software across backend systems, product interfaces and AI-powered applications.</p><div className="hero-actions"><a className="button button-dark" href="#work">View work <span>↓</span></a><a className="button button-line" href={resumeUrl} target="_blank" rel="noreferrer">Resume ↗</a></div><div className="hero-socials"><a href={githubUrl} target="_blank" rel="noreferrer">GitHub ↗</a><a href={linkedinUrl} target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></div></section>
    <section className="currently section-wrap" id="edinburgh"><SectionHeading index="01" intro="A new academic chapter, grounded in production engineering.">Currently</SectionHeading><div className="currently-card"><span className="currently-kicker">The University of Edinburgh</span><div><h3>MSc Computer Science</h3><p>2026—2027 <i>·</i> Starting September 14, 2026</p></div><p className="currently-copy">Pursuing a one-year MSc while continuing to build software and explore systems, software engineering and AI.</p></div></section>
    <section className="experience section-wrap" id="experience"><SectionHeading index="02" intro="Full-stack feature ownership across a production running-event ecosystem.">Experience</SectionHeading><div className="experience-layout"><div className="company-lockup"><p className="eyebrow">Oct 2025 — Jun 2026 / Mumbai, India</p><h3>Software<br />Engineer</h3><p>Fitpage <i>/</i> IndiaRunning</p></div><div className="experience-content"><p className="experience-lead">Worked across a seven-repository production ecosystem spanning NestJS services, React and Next.js applications, shared data layers and integrations.</p><ul><li>Owned substantial features from API and data modelling through frontend workflows and production release.</li><li>Built across backend and frontend using TypeScript, NestJS, PostgreSQL/TypeORM, React, Next.js, Redis and Bull.</li><li>Shipped product systems involving payments, attribution, notifications, commerce, authentication and user-facing event workflows.</li><li>Integrated third-party services while keeping critical product flows resilient and asynchronous where appropriate.</li></ul><div className="metric-row"><div><strong>7</strong><span>repositories</span></div><div><strong>463</strong><span>commits</span></div><div><strong>15+</strong><span>substantial features</span></div></div></div></div></section>
    <section className="selected-work section-wrap" id="work"><SectionHeading index="03" intro="A few production systems I designed and built across the stack.">Selected work</SectionHeading><div className="work-grid">{caseStudies.map(study => <CaseStudy key={study.title} study={study} onOpen={setActiveStudy} />)}</div><div className="ecosystem"><div><span className="eyebrow">Conceptual production ecosystem</span><h3>Comfortable working across the seams.</h3><p>From a consumer or organiser action to the services, data, async work and external integrations behind it.</p></div><FlowDiagram type="notifications" /></div></section>
    <section className="projects section-wrap" id="projects"><SectionHeading index="04" intro="Things I build because the problem keeps me interested.">Independent projects</SectionHeading><div className="penvault"><div className="penvault-content"><span className="eyebrow">Featured independent product</span><h3>PenVault</h3><p>A platform built around reading, writing, discovering and engaging with stories.</p><div className="tags"><span>Python</span><span>Flask</span><span>PostgreSQL</span><span>Supabase</span></div><a className="text-button" href="https://penvault.co" target="_blank" rel="noreferrer">Visit PenVault <span>↗</span></a></div><a className="project-image-link" href="https://penvault.co" target="_blank" rel="noreferrer"><img src="https://i.ibb.co/G40Sjpxn/image.png" alt="PenVault product interface" /></a></div><div className="project-list"><article><span>01</span><div><h3>MedNova</h3><p>A digital learning platform connecting doctors and students around lectures, notes and moderated content.</p></div><a href="https://med-nova-sable.vercel.app/" target="_blank" rel="noreferrer">View ↗</a></article><article><span>02</span><div><h3>Flicksify</h3><p>A personal media library for tracking movies, shows, anime, manga and novels.</p></div><a href="https://github.com/sahilshaikhh202/Flicksify" target="_blank" rel="noreferrer">GitHub ↗</a></article></div></section>
    <section className="skills-section section-wrap" id="skills"><SectionHeading index="05" intro="Technologies in service of dependable product systems—not a logo collection.">Engineering stack</SectionHeading><div className="skills-list">{skills.map(([label, value]) => <div key={label}><h3>{label}</h3><p>{value}</p></div>)}</div></section>
    <section className="education section-wrap" id="about"><SectionHeading index="06">Education & direction</SectionHeading><div className="education-layout"><div><span className="eyebrow">2026 — 2027</span><h3>University of Edinburgh</h3><p>MSc Computer Science</p></div><div className="timeline"><div><span>2023</span><p>Undergraduate foundation</p></div><div><span>2025</span><p>Software Engineer<br />Fitpage / IndiaRunning</p></div><div className="timeline-current"><span>2026</span><p>MSc Computer Science<br />University of Edinburgh</p></div><div><span>2027</span><p>Next chapter</p></div></div></div></section>
    <section className="about section-wrap"><SectionHeading index="07">How I build</SectionHeading><div className="about-layout"><h3>I like problems that<br /><em>cross layers.</em></h3><div><p>My best work tends to happen where database design, API contracts, frontend state, async processing and external services all need to fit together.</p><div className="layer-chain"><span>Database</span><b>→</b><span>API</span><b>→</b><span>Frontend</span><b>→</b><span>Async</span><b>→</b><span>External services</span></div><p className="about-secondary">I’m interested in building systems that sit between product and engineering—then using deeper computer science study to make those systems more thoughtful and robust.</p></div></div><div className="notes"><span className="eyebrow">Engineering notes</span><p>A home for considered writing about systems, software engineering and what I learn while building. Coming soon.</p></div></section>
    <Contact /></main><Footer githubUrl={githubUrl} linkedinUrl={linkedinUrl} />{activeStudy && <CaseStudyModal study={activeStudy} onClose={() => setActiveStudy(null)} />}</div>;
}
export default App;
